# environment.yml for conda base environment (pytorch docker image)
name: base

dependencies:
  - matplotlib==3.8.4
  - pip==23.3.1
  - python-dotenv==0.21.0
  - pytest==7.4.0
  - rich==13.3.5
  - tqdm==4.65.0
  - pip:
    - auraloss[all]
    - dawdreamer==0.8.3
    - hydra-core==1.3.2
    - hydra-colorlog==1.2.0
    - lightning==2.2.3
    - omegaconf==2.3.0
    - optuna==3.5.0
    - mido==1.3.3
    - pandas==2.2.2
    - pedalboard==0.9.16
    - timm==0.9.10 # 0.4.12 might be required for passt 
    - torchopenl3==1.0.1
    - umap-learn==0.5.6
    - wandb==0.16.5